### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kenmaples**
Note potential limitation for Home Assistant (Hass.io)
Add HACS details.

### CODE REVIEW

**Comment by kenmaples** [comment]
Thank you. Corrected.

**Comment by sagitt** [comment]
is possible add it to hacs?

**Comment by towerhand** [comment]
Yes

**Comment by sagitt** [comment]
well, but where i can found the access token?

**Comment by towerhand** [comment]
When you are setting up the integration, add your language and leave the token blank. On the 2nd step it will give you a link to add to your browser and log in your account, copy the url after logging in (should be a blank page on your browser) and add it as directed.

**Comment by sagitt** [comment]
> When you are setting up the integration, add your language and leave the token blank. On the 2nd step it will give you a link to add to your browser and log in your account, copy the url after logging in (should be a blank page on your browser) and add it as directed.

done. i hope will be possible send actions to the washer and maybe have a dryer and fridge in future.

this is my models:


LG   GMJ936NSHV
LG F4J7VY1W
LG RC90U2AV4Q

Washer and dryer you know what can do, fridge can set temperature and receiver alerts (doors)

**Pull request merged**
